layout_spectrum: 0.5125448
color:
  saturation: 0.8315412
  lightness: 1
  brandStrength: 0.6397849
  brandColors:
    - '#160D0B'
    - '#544139'
    - '#B4C5D0'
    - '#D7541E'
    - '#FAFFFF'
  rhythmicContrast: 0.1863799
typography_spectrum: 0.05734767
name: SarahYukie
